import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/ui/header";
import { AuthProvider } from "@/providers/auth";
import Footer from "@/components/ui/footer";
import CardProvider from "@/providers/cart";
import { Toaster } from "@/components/ui/sonner";
import CartModal from "@/components/ui/CartDialog";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-full flex-col">
          <AuthProvider>
            <CardProvider>
              <Header />
              <div className="flex-1">{children}</div>
              <Footer />
              <Toaster richColors />
            <CartModal />
            </CardProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
